### ISSUE TITLE
Create DSpace 6 instance

### ISSUE THREAD

**Issue by hortongn** [uclibs/uc_drc#2]
Find the best way to get a DSpace 6 instance running.

Would be nice if individuals could spin this up easily on their own machines, but we will also want an instance running on a sandbox somewhere.

**Comment by crowesn** [comment]
https://dspace-labs.github.io/DSpace-Docker-Images/docker-compose-files/dspace-compose/
https://dspace-labs.github.io/DSpace-Docker-Images/documentation/run.DSpace6.html

**Comment by crowesn** [comment]
@scherztc 

Success: followed instructions for setup from ^^

```
git clone https://github.com/DSpace-Labs/DSpace-Docker-Images.git
cd DSpace-Docker-Images/docker-compose-files/dspace-compose
docker-compose -p d6 -f docker-compose.yml -f d6.override.yml pull
```

<img width="1017" alt="Screen Shot 2020-03-17 at 7 20 27 AM" src="https://user-images.githubusercontent.com/1069588/76851742-2eb3d100-6820-11ea-823c-e2b636063ade.png">

**Comment by crowesn** [comment]
Planning deploy (3/30/2020) of test dspace instance to ECS/EC2. Not using Fargate since there are issues with ssh access to the app. There may be opportunity to mix Fargate and EC2 once we learn more about the ECS platform.

**Links**

1. https://wiki.lyrasis.org/pages/viewpage.action?pageId=78152613
1. https://github.com/aws/containers-roadmap/issues/187
1. https://stackoverflow.com/questions/52310447/is-it-possible-to-ssh-into-fargate-managed-container-instances

**Comment by crowesn** [comment]
https://calculator.aws/#/estimate?id=9b08ea391890f77304acd5d3e401bb8b939671bd

**Comment by crowesn** [comment]
http://ec2-13-58-115-54.us-east-2.compute.amazonaws.com:8080/xmlui/
